### ISSUE TITLE
Add support for arrays as query parameters

### ISSUE THREAD

**Issue by arw180** [marcgibbons/django-rest-swagger#312]
It doesn't seems to be possible to document query parameters that can take a list of values in the form:
<code>
?name=jack&name=jill
</code>

From what I can tell, this has been supported in swagger-api since ~April 2014: https://github.com/swagger-api/swagger-ui/issues/118

I suspect this is also relevant (http://django-rest-swagger.readthedocs.org/en/latest/yaml.html#parameters): "Exceptions: $ref, items, and uniqueItems are not currently supported."

Are there plans to support multiple query parameters of the same name in the future?

**Comment by cancan101** [comment]
In the YAML docstring, I set:
```
          paramType: query
          allowMultiple: true
```
and I believe that works.

**Comment by arw180** [comment]
I've tried that, but the allowMultiple param doesn't seem to have an effect. The value field in the generated documentation form is a single text field (with no option to add/create additional text fields), and any separators I try to add just get url-encoded, so I'm not sure how to add multiple parameters of the same name in the query string

**Comment by Nizebulous** [comment]
+1 Anybody know how to do this?

**Comment by pedrospdc** [comment]
@Nizebulous  I just got it working.
It only works if you have a defined set of possible values.
```yaml
            - name: publish_to
              type: string
              allowMultiple: true
              enum:
                  - developer
                  - infocenter
              paramType: form
              required: true
              description: publish to the specified destinations
```
