### ISSUE TITLE
parameters_strategy: replace fails with paramType: body

### ISSUE THREAD

**Issue by jonzlin95** [marcgibbons/django-rest-swagger#349]
The parameters_strategy replace fails when the only parameters that are created are of paramType body. To reproduce, create a serializer with fields, and then write documentation similar to

```YAML
serializer: ModelSerializer
parameters_strategy: replace
parameters:
  - name: json
    paramType: body
```

However the replacement will work with

```YAML
serializer: ModelSerializer
parameters_strategy: replace
parameters:
  - name: ignore_me
    type: string
  - name: json
    paramType: body
```
