### ISSUE TITLE
docstring for nested JSON custom response

### ISSUE THREAD

**Issue by som-soni** [marcgibbons/django-rest-swagger#416]
Hi,

How do we define a custom JSON response (type) in docstring with nested JSON. The documentation has an example for simple types (string/url etc.).

Thanks

**Comment by mazurov** [comment]
The same question have been just raised for me too

**Comment by Pankul-Mittal** [comment]
Hi mazurov,

Did you fix this issue?
if you have a solution for it. Please let me know.

Thanks,

**Comment by rudeb0t** [comment]
I have tried using the format described here: http://idratherbewriting.com/2015/12/10/ten-realizations-using-swagger-and-swagger-ui/ like so:

```
        type:
            status:
                type: integer
                required: true
                description: HTTP status code of the response. Should always be
                             200 on success.
            token:
                required: true
                type: object
                properties:
                    name:
                        type: string
                        required: true
                    value:
                        type: string
                        required: true
```

But it does not seem to work and only produces:

```
MyAPIGetResponse {
    status (integer): HTTP status code of the response. Should always be 200 on success.,
    token (object)
}
```

What's the proper syntax to get this working?
