### ISSUE TITLE
Enabling explicit swagger style model definition in yaml string

### ISSUE THREAD

**Issue by DheerendraRathor** [marcgibbons/django-rest-swagger#468]
I had this requirement for my project where using serializers for response was quite heavy and I was returning python dictionary with lot of nesting. So I need to use custom models defs with `$ref`. 

OpenAPI specs supports model definition and in django-rest-swagger model defs are generated from serializers only. I went through source code and found that implementing this feature is quite straightforward and very useful for swagger docs. 

Here is what I implemented and tested:
https://github.com/DheerendraRathor/django-rest-swagger/commit/d257cd37d43a8cbd26066705555f754ba2abc335

Here is an example of model def in docstring:
```
models:
    MyResponseModel:
        id: MyResponseModel
        properties:
            uuid:
                type: string
                description: UUID4 field
            created_at:
                type: string
                format: date-time
                description: Instance creation time
            item_count:
                type: integer
        required:
            - uuid
            - created_at
            - item_count

# Usage
type:
    results:
        type: array
        items:
            $ref: MyResponseModel
```
