### ISSUE TITLE
Cannot customize UI template in v2.2.0

### ISSUE THREAD

**Issue by XueWei** [marcgibbons/django-rest-swagger#770]
It seems the document "UI Customization" https://django-rest-swagger.readthedocs.io/en/latest/customization/ doesn't work for the new version (I am using v2.2.0)

I want to change the logo with {% block logo %}, but it doesn't work. 

Could anyone know how to customize logo (UI) in v2.2.0?

**Comment by frennkie** [comment]
Having issues too. This seems to be outdated https://django-rest-swagger.readthedocs.io/en/latest/customization/ as there is no base.html anymore.

**Comment by ju5t** [comment]
The documentation is definitely outdated, base.html doesn't exist, index.html does. It doesn't have a logo layout block though.

We need to override the version it sends to the API. Adding the code does add it to the source of the page but it isn't added to the request.

**Comment by ellisist** [comment]
I might be misunderstanding something, but I believe you can still customize the UI by overwriting `index.html`, it just doesn't extend `base.html` any more. The best way I've found to customize, which seems to work, is to copy the `index.html` provided by Swagger into your templates file and just change what you need to on the copy.

It's not as elegant or readable as the old way, but it works for now.

**Comment by mmmcorpsvit** [comment]
i tto try customized UI, and this work:
templates\rest_framework_swagger\index.html
```html
{% extends "base.html" %}
{% load i18n %}

{% load static %}
{#{% extends "rest_framework_swagger/index.html" %}#}

{% block extra_styles %}
    <link href="{% static 'rest_framework_swagger/bundles/vendors.bundle.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'rest_framework_swagger/bundles/app.bundle.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static '/assets/css/fix_rest_framework_swagger.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block main %}
  <div id="rest-swagger-ui"></div>
  {% csrf_token %}
{% endblock main %}


{% block extra_scripts %}
    <script>
        window.drsSettings = {{ drs_settings|safe }};
        window.drsSpec = {{ spec|safe }};
    </script>

    <script src="{% static 'rest_framework_swagger/bundles/vendors.bundle.js' %}"></script>
    <script src="{% static 'rest_framework_swagger/bundles/app.bundle.js' %}"></script>
{% endblock extra_scripts %}
```

customize css (fixed for integrate with bootstrap 4):
```css
/*Исправления интерфейса для swagger*/

.wrapper {
    height: unset;
}

.main-panel {
    width: 100%;
}

.main-panel > .content {
    margin-top: 0;
}

/*Цвет фона*/
#rest-swagger-ui {
    background-color: #fff;
}

.col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-10, .col-11, .col-12, .col, .col-auto, .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm, .col-sm-auto, .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-md, .col-md-auto, .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg, .col-lg-auto, .col-xl-1, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5, .col-xl-6, .col-xl-7, .col-xl-8, .col-xl-9, .col-xl-10, .col-xl-11, .col-xl-12, .col-xl, .col-xl-auto {
    width: unset;
}

.swagger-ui .parameters-col_description input[type="text"] {
    max-width: unset;
}

/*Скрыть заголовок АПИ*/
.main {
    display: none;
}

/*Скрыть схему АПИ*/
.scheme-container {
    display: none;
}

/*Скрыть язык*/
#language_picker {
        display: none;
}

```
![bcd1acb563](https://user-images.githubusercontent.com/9638835/46700338-3d5a8980-cc25-11e8-9a85-8b7c87743cf9.jpg)

Like if help)
